name: CD para o render

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Chamar o Deploy Hook do Render
        run: curl -X POST ${{secrets.RENDER_DEPLOY_HOOK}}
