version: '3.8'


services:


  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_catalog_local_db



  api:
    build: .
    container_name: catalog_api
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080-8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/product_catalog_local_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SENHA_SECRETA: 2222222